# Generated by Django 4.2.19 on 2025-02-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
