# Generated by Django 4.2.19 on 2025-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='goal',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
